# This workflow will run the Terraform configuration file
# and creates a repository for Amazon ECR
name: Dev Amazon ECR Setup

on: workflow_dispatch

permissions:
  id-token: write
  contents: write

jobs:
  setup-dev-ecr:
    name: setup-dev-ecr
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ${{ vars.ECR_SETUP_DIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    # On push to "main", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
